r"""
Sage variables definitions for Gentoo
"""
SAGE_ETC     = "@GENTOO_PORTAGE_EPREFIX@/etc"
SAGE_SHARE   = "@GENTOO_PORTAGE_EPREFIX@/usr/share/sage"
SAGE_DOC     = "@GENTOO_PORTAGE_EPREFIX@/usr/share/doc/@GENTOO_PORTAGE_PF@"

SAGE_EXTCODE = "@GENTOO_PORTAGE_EPREFIX@/usr/share/sage/ext"
GAP_ROOT_DIR = "@GENTOO_PORTAGE_EPREFIX@/usr/share/gap"
THEBE_DIR    = "@GENTOO_PORTAGE_EPREFIX@/usr/share/thebe"
JMOL_DIR     = "@GENTOO_PORTAGE_EPREFIX@/usr/share/sage-jmol-bin"
JSMOL_DIR    = "@GENTOO_PORTAGE_EPREFIX@/usr/share/jsmol"
MATHJAX_DIR  = "@GENTOO_PORTAGE_EPREFIX@/usr/share/mathjax"
MTXLIB       = "@GENTOO_PORTAGE_EPREFIX@/usr/share/meataxe"
SINGULARPATH = "@GENTOO_PORTAGE_EPREFIX@/usr/share/singular"
PPLPY_DOCS   = "@GENTOO_PORTAGE_EPREFIX@/usr/share/doc/@PPLY_DOC_VERS@/html"
