--- Makefile.am~	2008-05-16 16:41:18.000000000 +0200
+++ Makefile.am	2008-08-16 23:39:30.717711748 +0200
@@ -23,8 +23,10 @@
 # which isn't very clean, but it seems to be the only way of getting them
 # in front of the full list of input object files. Automake does not allow
 # modifying the ecm_OBJECTS variable directly.
 ecm_LDFLAGS = 
-ecm_LDFLAGS += $(ECM_FASTOBJ)
+libecm_la_LIBADD = @LIBGOMP@
+ecm_LDADD = $(LDADD) 
+ecm_LDADD += $(ECM_FASTOBJ) 
 
 tune_CPPFLAGS = -DTUNE $(AM_CPPFLAGS)
 # tune_LDADD =
