#!/bin/sh

# check which version of Sage is installed (if at all)
SAGE_ATOM=$(portageq best_version / sci-mathematics/sage)

# if Sage is not installed there is nothing left to do
if [[ ${SAGE_ATOM} = "" ]]; then
	echo "sci-mathematics/sage is not installed, exiting"
	exit 0
fi

# save the version of installed Sage
declare -a SAGE_VERSION=( $(qatom ${SAGE_ATOM}) )

# print out ebuild version
echo "SAGE_VERSION=${SAGE_VERSION[2]}"

# list dependencies of Sage
SAGE_DEPENDENCIES=( $(qdepends ${SAGE_ATOM}) )

# remove first element
unset SAGE_DEPENDENCIES[0]

# temporary array
declare -a OUTPUT=()

for i in ${SAGE_DEPENDENCIES[@]} ; do
	# remove '>=' in front of atoms
	i=${i#>=}
	# remove '=' in front of atoms
	i=${i#=}
	# remove '[..]' at the end of atoms
	i=${i%\[*\]}
	# remove '*' at the end of atoms
	i=${i%\*}

	# append
	OUTPUT=( ${OUTPUT[@]} $i )
done

# sort dependencies
SAGE_DEPENDENCIES=( $(echo ${OUTPUT[@]} | tr ' ' '\n' | sort) )

for i in ${SAGE_DEPENDENCIES[@]} ; do
	# atomize packages ...
	ATOMIZED=( $(qatom $i) )
	# and extract unversioned atom
	UNVERSIONED_ATOM=${ATOMIZED[0]}/${ATOMIZED[1]}

	# compare installed and required packages
	qatom --compare $(portageq best_version / ${UNVERSIONED_ATOM}) $i
done
