#!/bin/bash -x

TMP="$(mktemp -d)"

ACTIONS=(
#	--update
	--update-use-local-desc
)

egencache --repo=sage-on-gentoo --portdir-overlay="$(dirname $0)"/.. \
	--cache-dir="${TMP}" ${ACTIONS[@]}

rm -rf "${TMP}"
