#!/bin/bash

set -e

offset=100
cd "$(dirname "$0")/.." # change to root of sage tree
IFS=$'\n'
pre=( $(find dev-lang/python -type f | \
    grep -v dev-lang/python/files/dynamic_class_copyreg_.*\\.patch) )
rm "${pre[@]}"
cp -r /usr/portage/dev-lang/python dev-lang/
for dst in dev-lang/python/*.ebuild; do
	case ${dst} in
		dev-lang/python/python-2.[6-9]*.ebuild)
			# keep this ebuild
			lastKeptEbuild="${dst}"
			;;
		*)
			rm "${dst}"
			continue
			;;
	esac
	patch --quiet --no-backup-if-mismatch -l "${dst}" <<'EOF'
--- python.ebuild
+++ python.ebuild
@@ -81,3 +80,10 @@
 	EPATCH_SUFFIX="patch" epatch "${WORKDIR}/${PV}"
 
+       if use sage; then
+		# patch pickle for sage http://bugs.python.org/issue7689
+		epatch "${FILESDIR}/dynamic_class_copyreg_py.patch"
+		EPATCH_OPTS="${EPATCH_OPTS} -l" \
+			epatch "${FILESDIR}/dynamic_class_copyreg_c.patch"
+	fi
+
 	sed -i -e "s:@@GENTOO_LIBDIR@@:$(get_libdir):g" \

EOF
        sed -i 's/^IUSE="/IUSE="sage /;
		s/^KEYWORDS="\(.*\)"/KEYWORDS="\1 ~amd64-linux ~x86-linux"/;
               ' "${dst}"
        if [[ $(grep '^IUSE="sage ' ${dst} | wc -l) -ne 1 ]]; then
            echo "Sed didn't apply cleanly to ${dst}" >&2
            exit 1
        fi
done

sed -i 's:</use>:\t<flag name="sage">Apply fix for issue7689'\
' reuired by sage.</flag>\n</use>:' dev-lang/python/metadata.xml

ebuild "${lastKeptEbuild}" digest
git add -A dev-lang/python
git status
